### ISSUE TITLE
Run url as output

### ISSUE THREAD

**Issue by mina-kleid** [aws-actions/aws-devicefarm-mobile-device-testing#2]
### Description
I can see that you generate the [run url ](https://github.com/aws-actions/aws-devicefarm-mobile-device-testing/blob/e4ed21081f0dc8c2d81302de85bee986bdf751dd/index.js#L390) and add it as a notice.
Would be very useful if it can be added to the outputs instead of a notice

### Use case
As part of our CI/CD we want to run UI Tests on device farm and notify our engineers in case of failure with the `run url` so our engineers can go to the run on AWS Console and find the failing tests

### Expected
Have the run url as an output from the action 

### Actual
I need to compute it in my job through extracting the run_id & project_id from the `arn` output and generating the url

### Suggested solution
Add the run_url as an output instead of a notice

**Comment by danjhd** [comment]
Yep, that makes sense.

**Comment by danjhd** [comment]
@mina-kleid Thank you for your feedback. We have incorporated this request into the v2-beta pre-release, please review and feedback as required:

[https://github.com/aws-actions/aws-devicefarm-mobile-device-testing/releases/tag/v2-beta](https://github.com/aws-actions/aws-devicefarm-mobile-device-testing/releases/tag/v2-beta)

**Comment by mina-kleid-mobile** [comment]
@danjhd Thanks for your fast response. Looks good 🚀

**Comment by mina-kleid** [comment]
@danjhd Thanks for your fast response & changes. Looks good to me 🚀

**Comment by danjhd** [comment]
Closing this with release of v2.0
